### ISSUE TITLE
Feed without value block results in stack trace

### ISSUE THREAD

**Issue by charabaruk** [valcanobacon/BoostCLI#2]
**Expected Result:** Title, URL, GUID, and Podcast Index feed ID shown, followed by "No Value Block" message without stack trace.

**Actual Result:**

```
> boostcli podcast 'https://www.absna6pack.com/?format=rss'
No Value Block
Traceback (most recent call last):
  File "C:\Users\chris\source\Repos\BoostCLI\venv\Scripts\boostcli-script.py", line 33, in <module>
    sys.exit(load_entry_point('BoostCLI', 'console_scripts', 'boostcli')())
  File "C:\Users\chris\source\Repos\BoostCLI\venv\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\chris\source\Repos\BoostCLI\venv\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\chris\source\Repos\BoostCLI\venv\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\chris\source\Repos\BoostCLI\venv\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\chris\source\Repos\BoostCLI\venv\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\chris\source\Repos\BoostCLI\venv\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\chris\source\repos\boostcli\src\cli\__init__.py", line 133, in podcast
    ["Title", podcast_value.podcast_title],
AttributeError: 'NoneType' object has no attribute 'podcast_title'
```

**Comment by valcanobacon** [comment]
@coldacid fixed https://github.com/valcanobacon/BoostCLI/commit/e4281bce7080142b55ed8f30ba6581391c373120 

```
% boostcli podcast 'https://www.absna6pack.com/?format=rss'
No Value Block
```

**Comment by charabaruk** [comment]
Looks good!
