### ISSUE TITLE
Can't send boosts after switch to lnd-grpc-client library

### ISSUE THREAD

**Issue by charabaruk** [valcanobacon/BoostCLI#5]
```
ERROR MESSAGE: failed to connect to all addresses
Traceback (most recent call last):
  File "C:\Users\chris\source\Repos\BoostCLI\venv\Scripts\boostcli-script.py", line 33, in <module>
    sys.exit(load_entry_point('BoostCLI', 'console_scripts', 'boostcli')())
  File "C:\Users\chris\source\Repos\BoostCLI\venv\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\chris\source\Repos\BoostCLI\venv\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\chris\source\Repos\BoostCLI\venv\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\chris\source\Repos\BoostCLI\venv\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\chris\source\Repos\BoostCLI\venv\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\chris\source\Repos\BoostCLI\venv\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\chris\source\repos\boostcli\src\cli\__init__.py", line 246, in boost
    payment.payment_hash.hex(),
AttributeError: 'NoneType' object has no attribute 'payment_hash'
```

**Comment by charabaruk** [comment]
Disregard, I didn't have the port forwarding enabled. (Although it would be really nice if BoostCLI would give a proper error message when it can't connect instead of crashing with stack trace.)
