### ISSUE TITLE
Error boosting a certain feed

### ISSUE THREAD

**Issue by dowodenum** [valcanobacon/BoostCLI#7]
https://www.podserve.fm/series/rss/2202/behind-the-schms.rss

edit: just tried again, also happens with podcastindex URL: https://podcastindex.org/podcast/150842

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/encodings/hex_codec.py", line 19, in hex_decode
    return (binascii.a2b_hex(input), len(input))
binascii.Error: Odd-length string

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/me/BoostCLI/venv/bin/boostcli", line 33, in <module>
    sys.exit(load_entry_point('BoostCLI', 'console_scripts', 'boostcli')())
  File "/home/me/BoostCLI/venv/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/me/BoostCLI/venv/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/me/BoostCLI/venv/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/me/BoostCLI/venv/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/me/BoostCLI/venv/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/me/BoostCLI/venv/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/me/BoostCLI/src/cli/__init__.py", line 329, in boost
    for i, payment in enumerate(payments):
  File "/home/me/BoostCLI/src/services/lightning_service.py", line 183, in pay_boost_invoice
    dest = codecs.decode(destination.receiver_address, "hex")
binascii.Error: decoding with 'hex' codec failed (Error: Odd-length string)
```

**Comment by cottongin** [comment]
```
❯ cd dev/BoostCLI
❯ source venv/bin/activate
❯ boostcli --macaroon admin.macaroon boost https://www.podserve.fm/series/rss/2202/behind-the-schms.rss
╭────────────────────────────────────────────────────────── Podcast ───────────────────────────────────────────────────────────╮
│          ,/     Behind the SchƎmƎs                                                                                           │
│        ,'/      e0ac9365-689c-5043-8804-15b9dfcc545a                                                                         │
│      ,' /       https://www.podserve.fm/series/rss/2202/behind-the-schms.rss                                                 │
│    ,'  /_____,  https://podcastindex.org/podcast/150842                                                                      │
│  .'____    ,'                                                                                                                │
│       /  ,'               Split                     Fees                                                                     │
│      / ,'        ThunderRoad          83%   Podcastindex.org  1%                                                             │
│     /,'          SirVoBlitz           10%   BoostCLI          1%                                                             │
│    /'            PaywallLink LNPAYco   3%                                                                                    │
│                  Podcast Index         3%                                                                                    │
│                  BoostBot              1%                                                                                    │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
amount (sats): 333
Sender name: cottongin
╭────────────────────────────────────────────────────────── Invoice ───────────────────────────────────────────────────────────╮
│  Recipient                                                              Address                                        sats  │
│  ThunderRoad                                                     03589f3d ... 74ac93e2                             270 .862  │
│  SirVoBlitz                                                      5i2agq6u ... nion9735                              32 .634  │
│  PaywallLink LNPAYco                                             033868c2 ... 41649735                               9 .790  │
│  Podcast Index                                                   03ae9f91 ... 56229735                               9 .790  │
│  BoostBot                                                        03d55f4d ... 80efaa67                               3 .263  │
│  Podcastindex.org                                                03ae9f91 ... 05e61a4a                               3 .330  │
│  BoostCLI                                                        03d55f4d ... 80efaa67                               3 .330  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────── Boost ────────────────────────────────────────────────────────────╮
│ cottongin                                                                                                                    │
│ 333 .000 sats                                                                                                                │
│                                                                                                                              │
│ BoostCLI test?                                                                                                               │
│                                                                                                                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Send? [y/n]: y
 ✅ ThunderRoad 68c18462 ... 6945ad35 fee=0 .008 total=270 .870 hops=2
⠧ SirVoBlitz ━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  14% 0:01:09
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/encodings/hex_codec.py", line 19, in hex_decode
    return (binascii.a2b_hex(input), len(input))
binascii.Error: Odd-length string

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/cottongin/dev/BoostCLI/venv/bin/boostcli", line 33, in <module>
    sys.exit(load_entry_point('BoostCLI', 'console_scripts', 'boostcli')())
  File "/Users/cottongin/dev/BoostCLI/venv/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/cottongin/dev/BoostCLI/venv/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/cottongin/dev/BoostCLI/venv/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/cottongin/dev/BoostCLI/venv/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/cottongin/dev/BoostCLI/venv/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/cottongin/dev/BoostCLI/venv/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/cottongin/dev/BoostCLI/src/cli/__init__.py", line 329, in boost
    for i, payment in enumerate(payments):
  File "/Users/cottongin/dev/BoostCLI/src/services/lightning_service.py", line 183, in pay_boost_invoice
    dest = codecs.decode(destination.receiver_address, "hex")
binascii.Error: decoding with 'hex' codec failed (Error: Odd-length string)
```

Same, reproducible

**Comment by dowodenum** [comment]
Error was related to source RSS: full URI was given instead of pubkey
